#Git Actions sample file
name: My Git actions file
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Sample output
          run: hostname
        - name: Install jq tool
          run: |
            sudo apt-get update
            sudo apt-get install terraform
        - name: Check installation status
          run: terraform --version





  
