#Git Actions sample file
name: My Git actions file
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Sample output
          run: hostname
        - name: Install jq tool
          run: |
            sudo apt update
            sudo apt install -y terraform
        - name: Check installation status
          run: terraform --version





  
