#Git Actions sample file
name: My Git actions file
on: push
jobs:
  build:
    runs-on: self-hosted
    steps:
        - name: Sample output
          run: hostname
        - name: Check installation status
          run: terraform --version
        - name: checkout
          uses: actions/checkout@v2






  
